### ISSUE TITLE
BrightHorizons Parsing Time Error

### ISSUE THREAD

**Issue by dwai90** [leocov-dev/tadpoles-backup#47]
I'm getting an error when running the latest build on docker compose running on M1 Mac.

`tadpoles-backup-download-1  | Cmd Error       : parsing time "\"2023-07-10\"" as "\"2006-01-02T15:04:05Z07:00\"": cannot parse "\"" as "T"
tadpoles-backup-download-1 exited with code 1`

**Comment by leocov-dev** [comment]
could you please provide more information? there is a flag `--debug` that may give more details about the point of failure.
I am using the default Go time parsing but if there is bad data (seems from your log msg that there is an extra set of quotes) then that is a problem and will require a custom parser.
I added BrightHorizons support with the aid of another user - I don't have the ability to test BrightHorizon myself.

**Comment by leocov-dev** [comment]
closing - any changes to Bright Horizons related code will be handled as part of https://github.com/leocov-dev/tadpoles-backup/issues/48
